apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-api
  template:
    metadata:
      labels:
        app: fastfood-api
    spec:
      containers:
        - name: fastfood-api
          image: guilhermemmnn/fastfood-api:latest   # Necessário fazer push da imagem docker no DockerHub
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fastfood-config
            - secretRef:
                name: fastfood-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"