apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
spec:
  selector:
    app: fastfood-api
  ports:
    - protocol: TCP
      port: 8080         # Porta interna do container
      targetPort: 8080   # Porta no container que será exposta
      nodePort: 30000    # Porta no nó (máquina local) para acessar o serviço
  type: NodePort         # Expondo o serviço como NodePort
  #type: LoadBalancer