apiVersion: v1
kind: Service
metadata:
  name: fastfood-api
spec:
  selector:
    app: fastfood-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32100
  type: NodePort