apiVersion: v1
kind: Secret
metadata:
  name: fastfood-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNwdw==
  FASTFOOD_MAIL_PASSWORD: dGR2ZSBlcHhpIHVpbWwgcm5zdQ==
