apiVersion: v1
kind: Service
metadata:
  name: payment-api
spec:
  selector:
    app: payment-api
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32101
  type: NodePort
