apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
data:
  POSTGRES_USER: "postgres"
  FASTFOOD_DATABASE_URL: "jdbc:postgresql://fastfood-database:5432/postgres"
  FASTFOOD_API_PORT: "8080"
  FASTFOOD_API_ENVIRONMENT: "dev-local"
  FASTFOOD_DATABASE_USER: "postgres"