apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-database-traffic
spec:
  podSelector:
    matchLabels:
      app: fastfood-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: fastfood-database
      ports:
        - protocol: TCP
          port: 5432